# frozen_string_literal: true

# JSON Web token
class JsonWebToken
  SECRET_KEY = Rails.application.secrets.secret_key_base.to_s

  # https://medium.com/binar-academy/rails-api-jwt-authentication-a04503ea3248
  # SECRET_KEY is the key for encoding and decoding tokens.
  # In the code above, we assign a secret key generated by default by rails application
  # into the SECRET_KEY variable.
  # SECRET_KEY must be secret and not to be shared.
  # Every time we’re doing some encoding and decoding using JWT,
  # we need to specify the SECRET_KEY.

  def self.encode(payload, exp = 24.hours.from_now) # 24
    payload[:exp] = exp.to_i
    JWT.encode(payload, SECRET_KEY) # :SECRET_KEY
  end

  def self.decode(token)
    decoded = JWT.decode(token, SECRET_KEY)[0]
    HashWithIndifferentAccess.new decoded
  end
end
